version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns: ['*']

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      npm-dependencies:
        patterns: ['*']

  - package-ecosystem: uv
    directory: /etl
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        patterns: ['*']
